# Site settings
title: Alwaystis Blog
name: Alwaystis Blog # your name
email: alwaystiys@163.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alwaystiys.github.io" # the base hostname & protocol for your site
#twitter_username: itisbenjamin1 # your Twitter username
github_username: alwaystiys # your Github username
#disqus_username: itisbenjamin # your disqus username

#google-analytics: UA-75034651-1 # add it if you have one

#skillstree: true # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
